<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Property Entity.
 */
class Property extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * @var array
     */
    protected $_accessible = [
        'builder_id' => true,
        'property_type_id' => true,
        'location_id' => true,
        'propertype_location_id' => true,
		'propertype_sublocation_id' => true,
        'name' => true,
        'url' => true,
        'small_info' => true,
        'heading2' => true,
        'heading3' => true,
        'property_subtype_id' => true,
        'location_text' => true,
        'project_status' => true,
        'tabs' => true,
        'recommended_property' => true,
        'area' => true,
        'availability' => true,
        'bhk' => true,
        'price' => true,
        'budgetmin' => true,
        'budgetmax' => true,
        'completion' => true,
        'sector_id' => true,
        'property_logo' => true,
        'property_logo_alt_tag' => true,
        'property_image' => true,
        'property_image_alt_tag' => true,
        'location_heading' => true,
        'location_image' => true,
        'location_detail' => true,
        'location_alt_tag' => true,
        'master_heading' => true,
        'master_image' => true,
        'master_alt_tag' => true,
        'site_heading' => true,
        'site_image' => true,
        'site_alt_tag' => true,
        'numbering_heading' => true,
        'numbering_image' => true,
        'numbering_alt_tag' => true,
		'keyplan_heading' => true,
        'keyplan_image' => true,
        'keyplan_alt_tag' => true,
        'overview' => true,
        'ebrochure_image' => true,
        'small_description' => true,
        'features' => true,
        'amenities' => true,
        'specification' => true,
        'ebrochure_pdf' => true,
        'ebrochure_desc' => true,
        'overview_heading' => true,
        'features_desc_heading' => true,
        'amenities_heading' => true,
        'specification_heading' => true,
        'ebrochure_heading' => true,
        'pricelist_heading' => true,
        'price_list_desc' => true,
        'application_heading' => true,
        'application_pdf' => true,
        'application_image' => true,
        'application_desc' => true,
        'gallery_heading' => true,
        'youtube_url' => true,
        'layout_heading' => true,
        'layout_image' => true,
        'layout_image_alt' => true,
        'posted_date' => true,
        'update_date' => true,
        'status' => true,
        'seo_title' => true,
       // 'seo_description' => true,
		'seo_description' => array('rule' => array('lengthBetween', 5, 15)),
        'seo_keyword' => true,
        'open_graph_tags' => true,
        'open_graph_status' => true,
        'upcoming_property' => true,
        'upcoming_priority' => true,
        'recent_launches' => true,
        'recent_priority' => true,
        'luxury_home' => true,
        'luxury_priority' => true,
        'affordable_home' => true,
        'affordable_priority' => true,
        'recommended' => true,
        'recommended_priority' => true,
        'hot_property' => true,
        'hot_priority' => true,
        'nri' => true,
        'nri_priority' => true,
        'subvention' => true,
        'subvention_priority' => true,
        'assured_return' => true,
        'assured_return_priority' => true, 
		'plp' => true,
        'plp_priority' => true,
        'builderwise_priority' => true,
        'ptypewise' => true,
        'builder' => true,
        'property_type' => true,
        'location' => true,
        'propertype_location' => true,
		'propertype_sublocation' => true,
        'property_subtype' => true,
        'sector' => true,
        'banners' => true,
        'floor_plan' => true,
        'price_management' => true,
        'property_galleries' => true,
		'project_of_the_month' => true,
		'project_of_the_month_banner' => true,
		'buyBack' => true,
		'buyBack_priority' => true,
		'monthlyRental' => true,
		'monthlyRental_priority' => true,
		'latitude' => true,
		'longitude' => true,
		'rating' => true,
		'reraid' => true,
		'offer_payment_plan'=> true,
		'tower_building'=> true,
		'site_area'=> true,
		'specification_title'=>true,
		'specification_description'=>true,
		'location_title'=>true,
		'location_description'=>true,
		'pricelist_title'=>true,
		'pricelist_description'=>true,
		'masterplan_title'=>true,
		'masterplan_description'=>true,
		'siteplan_title'=>true,
		'siteplan_description'=>true,
		'floorplan_title'=>true,
		'floorplan_description'=>true,
		'gallery_title'=>true,
		'gallery_description'=>true,
    ];
}
